export const exchanges = [
  {
    id: 'bybit',
    sigil: 'I',
    house: 'House of Sapphire Tide',
    name: 'Bybit',
    desc: 'Глубокая ликвидность и ровная механика входа. Маршрут для дисциплины и устойчивого темпа.',
    href: 'https://example.com/bybit',
    tone: 'sapphire',
    badge: 'Core Route',
    highlight: true,
  },
  {
    id: 'bitget',
    sigil: 'II',
    house: 'House of Silver Mirror',
    name: 'Bitget',
    desc: 'Гибкие сценарии и социальная динамика. Подходит тем, кто любит адаптивную тактику.',
    href: 'https://example.com/bitget',
    tone: 'silver',
    badge: 'Adaptive',
    highlight: false,
  },
  {
    id: 'mexc',
    sigil: 'III',
    house: 'House of Ember Bloom',
    name: 'MEXC',
    desc: 'Ранние листинги и высокий потенциал. Больше глубины — выше требования к риск-менеджменту.',
    href: 'https://promote.mexc.com/r/vu6RfizpRR',
    tone: 'violet',
    badge: 'High Potential',
    highlight: true,
  },
  {
    id: 'orbit',
    sigil: 'IV',
    house: 'House of Moon Orbit',
    name: 'Orbit',
    desc: 'Точечный маршрут для ручного отбора сетапов и спокойной, методичной работы.',
    href: 'https://www.ourbit.com/ru-RU/auth/signup?inviteCode=6B2LY7',
    tone: 'emerald',
    badge: 'Niche Route',
    note: '⚠️ Orbit: сайт и регистрация работают только с VPN.',
    highlight: false,
  },
];
