export const exchanges = [
  {
    id: 'bybit',
    name: 'Bybit',
    route: 'Sapphire Route',
    badge: 'Core',
    number: '01',
    href: 'https://www.bybit.com/invite?ref=W2DDND',
    refCode: 'W2DDND',
    tone: 'cyan',
    description: 'Базовый маршрут для ликвидного рынка, понятного интерфейса и дисциплинированной торговли.',
    points: ['Высокая ликвидность', 'Понятный старт', 'Для активной торговли'],
    featured: true,
  },
  {
    id: 'bitget',
    name: 'Bitget',
    route: 'Mirror Route',
    badge: 'Adaptive',
    number: '02',
    href: 'https://www.bitget.com/ru/referral/register?clacCode=GF5KD76T&from=%2Fru%2Fevents%2Freferral-all-program&source=events&utmSource=PremierInviter',
    refCode: 'GF5KD76T',
    tone: 'blue',
    description: 'Гибкий вариант для сравнения условий, инструментов, сценариев и спокойного входа.',
    points: ['Гибкие сценарии', 'Социальные механики', 'Адаптивная тактика'],
    featured: false,
  },
  {
    id: 'mexc',
    name: 'MEXC',
    route: 'Ember Route',
    badge: 'Early',
    number: '03',
    href: 'https://promote.mexc.com/r/vu6RfizpRR',
    refCode: 'vu6RfizpRR',
    tone: 'violet',
    description: 'Маршрут для ранних листингов и активного отбора сетапов с повышенным вниманием к риску.',
    points: ['Ранние листинги', 'Широкий выбор', 'Нужен риск-контроль'],
    featured: true,
  },
  {
    id: 'ourbit',
    name: 'Ourbit',
    route: 'Moon Route',
    badge: 'Niche',
    number: '04',
    href: 'https://www.ourbit.com/ru-RU/auth/signup?inviteCode=6B2LY7',
    refCode: '6B2LY7',
    tone: 'green',
    description: 'Нишевый маршрут для ручного отбора, спокойной методики и точечных решений.',
    points: ['Точечный выбор', 'Ручной подход', 'Работает через VPN'],
    note: 'Может потребоваться VPN.',
    featured: false,
  },
];
