export const exchanges = [
  {
    id: 'bybit',
    name: 'Bybit',
    house: 'Sapphire Route',
    badge: 'Core',
    sigil: 'I',
    tone: 'blue',
    href: 'https://www.bybit.com/invite?ref=W2DDND',
    refCode: 'W2DDND',
    desc: 'Основной маршрут для ликвидного рынка, понятного интерфейса и дисциплинированной торговли.',
    points: ['Высокая ликвидность', 'Удобный старт', 'Для активной торговли'],
    featured: true,
  },
  {
    id: 'bitget',
    name: 'Bitget',
    house: 'Mirror Route',
    badge: 'Adaptive',
    sigil: 'II',
    tone: 'silver',
    href: 'https://www.bitget.com/ru/referral/register?clacCode=GF5KD76T&from=%2Fru%2Fevents%2Freferral-all-program&source=events&utmSource=PremierInviter',
    refCode: 'GF5KD76T',
    desc: 'Гибкий вариант для тех, кто хочет сравнивать условия, инструменты и сценарии входа.',
    points: ['Гибкие сценарии', 'Социальные механики', 'Адаптивная тактика'],
    featured: false,
  },
  {
    id: 'mexc',
    name: 'MEXC',
    house: 'Ember Route',
    badge: 'Early',
    sigil: 'III',
    tone: 'violet',
    href: 'https://promote.mexc.com/r/vu6RfizpRR',
    refCode: 'vu6RfizpRR',
    desc: 'Маршрут для ранних листингов и более активного отбора сетапов с повышенным вниманием к риску.',
    points: ['Ранние листинги', 'Широкий выбор', 'Нужен риск-контроль'],
    featured: true,
  },
  {
    id: 'ourbit',
    name: 'Ourbit',
    house: 'Moon Route',
    badge: 'Niche',
    sigil: 'IV',
    tone: 'green',
    href: 'https://www.ourbit.com/ru-RU/auth/signup?inviteCode=6B2LY7',
    refCode: '6B2LY7',
    desc: 'Нишевый маршрут для ручного отбора и спокойной методичной работы.',
    points: ['Точечный выбор', 'Ручной подход', 'Работает через VPN'],
    note: 'Может потребоваться VPN.',
    featured: false,
  },
];

export const stats = [
  ['4', 'маршрута входа'],
  ['0', 'лишнего шума'],
  ['24/7', 'доступ к рынку'],
];

export const steps = [
  ['01', 'Сравни маршрут', 'Посмотри назначение каждой биржи и выбери подходящий сценарий.'],
  ['02', 'Проверь условия', 'Перед регистрацией проверь комиссии, ограничения, KYC и доступность в регионе.'],
  ['03', 'Входи по плану', 'Работай только с лимитами, риск-менеджментом и понятным торговым планом.'],
];
